name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: umran666/gh-action-contrib-snake@v1
        with:
          github_user_name: 'umran666'
          output_file: './output/github-contribution-grid-snake.svg'
