name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: platane/snk@v2
        id: snake-gif
        with:
          github_user_name: 'umran666'
          outputs_path: 'output/github-contribution-grid-snake.svg'
